# GoReleaser configuration for Homebrew tap
# https://goreleaser.com/customization/homebrew/

version: 2

# Since binaries are already built by Bun in the release workflow,
# we use GoReleaser only for Homebrew tap management
builds:
  - skip: true

# Configure Homebrew tap
brews:
  - name: open-composer

    # Target repository for the tap
    repository:
      owner: shunkakinoki
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

    # Download strategy - fetch pre-built binaries from GitHub releases
    download_strategy: CurlDownloadStrategy

    # Install script to extract and install the binary
    install: |
      arch = Hardware::CPU.arch.to_s
      os = OS.mac? ? "darwin" : "linux"

      # Map architecture to match binary naming
      arch_map = {
        "x86_64" => "x64",
        "arm64" => "arm64"
      }

      binary_arch = arch_map[arch] || arch
      binary_name = "open-composer-cli-#{os}-#{binary_arch}"

      # Download and extract the binary
      system "curl", "-fsSL", "-o", "#{binary_name}.zip",
        "https://github.com/shunkakinoki/open-composer/releases/download/{{ .Tag }}/#{binary_name}.zip"
      system "unzip", "-q", "#{binary_name}.zip"

      # Install the binary
      bin.install "#{binary_name}/bin/open-composer"

      # Create symlinks for alternate names
      bin.install_symlink bin/"open-composer" => "oc"
      bin.install_symlink bin/"open-composer" => "opencomposer"

    # Test to verify installation
    test: |
      system "#{bin}/open-composer", "--version"

    # Metadata
    homepage: "https://github.com/shunkakinoki/open-composer"
    description: "Open Composer CLI - AI-powered development workflow tool"
    license: "MIT"

    # Use the package name and version from the release tag
    url_template: "https://github.com/shunkakinoki/open-composer/releases/download/{{ .Tag }}/open-composer-cli-{{ .Os }}-{{ .Arch }}.zip"

    # Only include macOS since Homebrew is primarily for macOS
    skip_upload: auto
