name = "posthog-worker"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

workers_dev = true
account_id = "121992ad6957cb0370fbda3384957564"

[vars]
POSTHOG_HOST = "https://us.i.posthog.com"

[durable_objects]
bindings = [{ name = "RATE_LIMITER", class_name = "RateLimiter" }]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RateLimiter"]

[observability.logs]
enabled = true
