name: Install
on:
  release:
    types: [published]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to install (e.g., open-composer@1.0.0)'
        default: 'open-composer@latest'
        required: false
        type: string
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true
jobs:
  install-e2e-cli:
    if: (github.event.release.tag_name && startsWith(github.event.release.tag_name, 'open-composer@')) || (github.event.inputs.tag && startsWith(github.event.inputs.tag, 'open-composer@')) || github.event_name == 'schedule'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          - macos-latest
          - windows-latest
        arch:
          - x64
          - arm64
        exclude:
          # Skip arm64 on Windows (not widely supported yet)
          - os: windows-latest
            arch: arm64
      fail-fast: false
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.release.tag_name || github.event.inputs.tag || github.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v5
      - name: Install open-composer globally with retry
        uses: nick-fields/retry@v3
        with:
          timeout_seconds: 30
          max_attempts: 10
          command: npm install -g ${{ github.event.release.tag_name || github.event.inputs.tag || 'open-composer@latest' }}
      - name: Verify opencomposer command
        if: matrix.os != 'windows-latest'
        run: open-composer --version
        shell: bash
      - name: Verify opencomposer command (Windows)
        if: matrix.os == 'windows-latest'
        run: open-composer --version
        shell: cmd
  install-check:
    if: always()
    needs:
      - install-e2e-cli
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Alls Green
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
          allowed-skips: install-e2e-cli
