name: Install
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to install (e.g., open-composer@1.0.0)'
        required: false
        type: string
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true
jobs:
  install-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x64, arm64]
        exclude:
          # Skip arm64 on Windows (not widely supported yet)
          - os: windows-latest
            arch: arm64
      fail-fast: false
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag || github.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v5
      - name: Install opencomposer globally
        run: npm install -g opencomposer@${{ github.event.inputs.tag || 'latest' }}
      - name: Verify opencomposer command
        run: opencomposer --version
        shell: ${{ matrix.os == 'windows-latest' && 'cmd' || 'bash' }}
  install-check:
    if: always()
    needs:
      - install-test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Alls Green
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
