name: Release
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        type: string
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true
jobs:
  release-upload:
    if: startsWith(github.event.release.tag_name, 'open-composer@') || github.event.inputs.tag != ''
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.tag || github.ref }}
      - name: Setup Bun
        uses: shunkakinoki/actions/.github/actions/setup-bun@36c30e5cf16d45445c026abf8f71a437443cbd33
      - name: Build CLI Binary
        run: bun run prepublishOnly
        env:
          OPENCOMPOSER_VERSION: ${{ github.event.release.tag_name || github.event.inputs.tag }}
          RELEASE_ZIP_FILES: true
      - name: Upload Binary Assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ./packages/cli/dist/opencomposer-*.zip
          tag: ${{ github.event.release.tag_name || github.event.inputs.tag }}
          overwrite: true
  release-latest:
    needs: release-upload
    if: github.event_name == 'release' && startsWith(github.event.release.tag_name, 'open-composer@')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Update Release as Latest
        uses: actions/github-script@v7
        with:
          script: |
            // Get the release details
            const { owner, repo } = context.repo;
            const release_id = context.payload.release.id;

            // Get the release details
            const { data: release } = await github.rest.repos.getRelease({
              owner,
              repo,
              release_id
            });

            // Update the release to be marked as latest and non-prerelease
            await github.rest.repos.updateRelease({
              owner,
              repo,
              release_id,
              prerelease: false,
              make_latest: true
            });

            console.log(`Updated release ${release.tag_name} as latest`);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-check:
    if: always()
    needs:
      - release-upload
      - release-latest
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Alls Green
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
